restaurant_tracker/urls.py
from django.urls import path

from . import views

app_name = 'restaurant_tracker'
urlpatterns = [
    # ex: /restaurants/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /restaurants/1/
    path('<int:pk>/', views.RestaurantDetailView.as_view(), name='detail'),
    # ex: /restaurants/1/edit/
    path('<int:pk>/edit/', views.RestaurantEditView.as_view(), name='restaurant_edit'),
    # ex: /restaurants/create/
    path('create/', views.create_restaurant, name='restaurant_create'),
    # ex: /restaurants/1/delete/
    path('<int:pk>/delete/', views.RestaurantDeleteView.as_view(), name='restaurant_delete'),
    # ex: /restaurants/tags/
    path('tags/', views.TagIndexView.as_view(), name='tag_index'),
    # ex: /restaurants/tags/1/edit/
    path('tags/<int:pk>/edit/', views.TagEditView.as_view(), name='tag_edit'),
    # ex: /restaurants/tags/create/
    path('tags/create/', views.create_tag, name='tag_create'),
    # ex: /restaurants/tags/1/delete/
    path('tags/<int:pk>/delete/', views.TagDeleteView.as_view(), name='tag_delete'),
    # ex: /restaurants/1/menu_items/create/
    path('<int:pk>/menu_items/create/', views.get_new_menu_item, name='menu_item_create'),
]

restaurant_tracker/templates/restaurant_tracker/base_tag.html
{% comment %} {% extends "base.html" %} {% endcomment %}
{% load static %}
<html>
    <head>
        <script src="https://kit.fontawesome.com/9357b5b30a.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'restaurant_tracker/css/base_style.css' %}?v=4">
        <title>
            {% block title %}{% endblock title %} | Restaurant Tracker
        </title>
        <script src="{% static 'restaurant_tracker/js/jquery.are-you-sure.js' %}"></script>
    </head>
    <body>
    {% block content%} 
        <div class="topnav">
            <a href="/restaurants">Restaurant List</a>
            <a class="active" href="/restaurants/tags">Tags</a>
        </div>
        <main>
            <div id="content">
                {% block page %}
                {% endblock %}
            </div>
        </main>
    {% endblock content %}
    </body>
</html>

restaurant_tracker/templates/restaurant_tracker/boolean_snippet.html
{% if condition %}
    {{true_value}}
{% else %}
    {{false_value}}
{% endif %}

restaurant_tracker/templates/restaurant_tracker/index.html
{% extends "restaurant_tracker/base_restaurant.html" %}
{% load static %}
{% block title %}Restaurant List{% endblock title %}
{% block page %}
<h1>Restaurants</h1>
{% comment %} <input type="text" id="search-bar" onkeyup="myFunction()" placeholder="Search restaurants..."> {% endcomment %}
{% if restaurant_list %}
    <table id="restaurant-table">
        <tr>
            <th>Restaurant Name</th>
            <th>Rating</th>
            <th>Price</th>
            <th>Tags</th>
            <th>Open/Closed</th>
        </tr>
        <tr>
            <td colspan="5">
                <section>
                    <a class="add-new" href="{% url 'restaurant_tracker:restaurant_create' %}">Add restaurant</a>
                </section>
            <td>
        </tr>
        {% for restaurant in restaurant_list %}
            <tr>
                <td id="name-column">{{ restaurant.name }}</td>
                <td id="rating-column">
                    {% if restaurant.visited %}
                        {% include "restaurant_tracker/star_snippet.html" with rating=restaurant.rating %}
                    {% else %}
                        <span>N/A</span>
                    {% endif %}
                </td>
                <td id="price-column">
                    {% include "restaurant_tracker/price_snippet.html" with price=restaurant.price %}
                </td>
                <td id="tag-column">
                    {% for tag in restaurant.tags.all %}
                        {% include "restaurant_tracker/tag_display_snippet.html" with tag=tag%}
                    {% endfor %}
                </td>
                <td id="open-closed-column">
                    {% include "restaurant_tracker/restaurant_open_closed_snippet.html" with is_open=restaurant.is_open%}
                </td>
                <td class="overlay-link">
                    {% comment %} <div class="overlay-link"> {% endcomment %}
                        <a href="{% url 'restaurant_tracker:detail' restaurant.id %}">Link to restaurant</a>
                    {% comment %} </div> {% endcomment %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <section>
        <a class="add-new" href="{% url 'restaurant_tracker:restaurant_create' %}">Add restaurant</a>
    </section>
    <p> No restaurants are available.</p>
{% endif %}
<div id="filter-sidebar">

</div>
{% comment %} <script>
    function myFunction() {
    // Declare variables
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("restaurantList");
    li = ul.getElementsByTagName('li');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
        } else {
        li[i].style.display = "none";
        }
    }
    }
</script> {% endcomment %}
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/menu_items_edit.html
{% extends "restaurant_tracker/base_restaurant.html" %}
{% load static %}
{% block page %}
<form method="post">
    <table>
        {{ formset }}
    </table>
</form>
<a href="{% url 'restaurant_tracker:detail' restaurant.id %}">Exit</a>
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/price_rating_widget.html
{% load static %}
<span id="id_price-rating-{{ widget.name }}" class="price-rating">
    {% for price in prices %}
        <label for="{{ widget.name }}-{{ forloop.counter0 }}"><i class="fa-solid fa-dollar-sign"></i></label>
        <input type="radio" name="{{ widget.name }}" id ="{{ widget.name }}-{{ forloop.counter0 }}"
            value ="{{ price }}" {% if widget.value == price|stringformat:'i' %}checked{% endif %} />
    {% endfor %}
</span>
<link rel="stylesheet" href="{% static 'restaurant_tracker/css/price_rating_style.css' %}" />

restaurant_tracker/templates/restaurant_tracker/price_snippet.html
{% load restaurant_tracker_extras %}
{% with end=price|add:1 %}
{% for index in 1|get_range:end%}
        <i class="fa-solid fa-dollar-sign"></i>
{% endfor %}
{% endwith %}

restaurant_tracker/templates/restaurant_tracker/restaurant_confirm_delete.html
{% extends "restaurant_tracker/base_restaurant.html" %}

{% block page %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Yes">
    <a href="{% url 'restaurant_tracker:restaurant_edit' restaurant.id %}">No</a>
</form>
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/restaurant_detail.html
{% extends "restaurant_tracker/base_restaurant.html" %}
{% load restaurant_tracker_extras %}
{% block title %}{{restaurant.name}}{% endblock title %}
{% block page %}
<div class="flexcol" id="restaurant-container">
    <div id="title-content">
        <h1 class="inline-h1">{{ restaurant.name }}</h1>
        {% include "restaurant_tracker/restaurant_open_closed_snippet.html" with is_open=restaurant.is_open%}
        <a href="{% url 'restaurant_tracker:restaurant_edit' restaurant.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
        <a href="{% url 'restaurant_tracker:restaurant_delete' restaurant.id %}"><i class="fa-solid fa-trash"></i></a>
        <div class="all-tags-display" style="display:block; max-width:300px">
            {% if restaurant.tags.count > 0 %}
                {% for tag in restaurant.tags.all %}
                    {% include "restaurant_tracker/tag_display_snippet.html" with tag=tag%}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="flexrow">
        <div class="detail-field-container{% if not restaurant.visited %} hidden {% endif %}">
            <span class="detail-field-label">Rating: </span>
            <span>{% include "restaurant_tracker/star_snippet.html" with rating=restaurant.rating %}</span>
        </div>
        <div class="detail-field-container">
            <span class="detail-field-label">Price: </span>
            <span>{% include "restaurant_tracker/price_snippet.html" with price=restaurant.price %}</span>
        </div>
    </div>
    <div class="flexrow{% if not restaurant.visited %} hidden {% endif %}">
        <div class="detail-field-container">
            <span class="detail-field-label">Service Speed: </span>
            <span>{% include "restaurant_tracker/speed_snippet.html" with restaurant=restaurant %}</span>
        </div>
        <div class="detail-field-container">
            <span class="detail-field-label">Service Comments: </span>
            <span>{{restaurant.service|string_or_default:"N/A"}}</span>
        </div>
    </div>
    <div class="flexcol">
        <span class="detail-field-label">Comments</span>
        <span>{{ restaurant.comment|string_or_default:"No comments." }}</span>
    </div>
    {% comment %} <p>Latitude: {{ restaurant.latitude }}</p>
    <p>Longitude: {{ restaurant.longitude }}</p> {% endcomment %}
    <div class="{% if not restaurant.visited %} hidden {% endif %}">
        {% if restaurant.get_menu_items.count > 0 %}
            <hr>
            <h2>Menu Items</h2>
            <table id="menu-items-table">
            <tr>
                <th>Name</th>
                <th>User</th>
                <th>Date</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Comment</th>
            </tr>
            {% for menu_item in restaurant.get_menu_items %}
                <tr>
                    <td id="name-column">{{menu_item.name}}</td>
                    <td id="user-column">{{menu_item.user}}</td>
                    <td id="date-column">{{menu_item.date}}</td>
                    <td id="price-column">{{menu_item.price|currency}}</td>
                    <td id="rating-column">{% include "restaurant_tracker/star_snippet.html" with rating=menu_item.rating %}</td>
                    <td id="comment-column">{{menu_item.comment}}</td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p> No menu items.</p>
        {% endif %}
    </div>
</div>
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/star_rating_widget.html
{% load static %}
{% load restaurant_tracker_extras %}
<span id="id_star-rating-{{ widget.name }}" class="star-rating">
    {% for star in stars %}
        {% if halfStars %}
            {% if star|divisibleby:2%}
                <label class="star-even" for="{{ widget.name }}-{{ forloop.counter0 }}"><i class="fa-solid fa-star-half"></i></label>
            {% else %}
                <label class="star-odd" for="{{ widget.name }}-{{ forloop.counter0 }}"><i class="fa-solid fa-star-half"></i></label>
            {% endif %}
        {% else %}
            <label for="{{ widget.name }}-{{ forloop.counter0 }}"><i class="fa-solid fa-star"></i></label>
        {% endif %}
        <input type="radio" name="{{ widget.name }}" id ="{{ widget.name }}-{{ forloop.counter0 }}"
            value ="{{ star }}" {% if widget.value == star|stringformat:'i' %}checked{% endif %} />
    {% endfor %}
</span>
<link rel="stylesheet" href="{% static 'restaurant_tracker/css/star_rating_style.css' %}" />

restaurant_tracker/templates/restaurant_tracker/star_snippet.html
{% load restaurant_tracker_extras %}
{% with end=rating|add:1 %}
{% for index in 2|get_range:end%}
    {% if index|divisibleby:2%}
        <i class="fa-solid fa-star"></i>
    {% endif %}
{% endfor %}
{% endwith %}
{% if rating|divisibleby:2%}
{% else %}
    <i class="fa-solid fa-star-half"></i>
{% endif %}

restaurant_tracker/templates/restaurant_tracker/tag_confirm_delete.html
{% extends "restaurant_tracker/base_tag.html" %}

{% block page %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'restaurant_tracker:tag_edit' tag.id %}">No</a>
</form>
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/tag_display_snippet.html
{% if tag.is_light_color %}
    <span class="tag-display" style="color:black; background-color:{{tag.color}};">{{ tag.name }}</span>
{% else %}
    <span class="tag-display" style="color:white; background-color:{{tag.color}};">{{ tag.name }}</span>            
{% endif %}

restaurant_tracker/templates/restaurant_tracker/tag_edit.html
{% extends "restaurant_tracker/base_tag.html" %}
{% block title %}Edit - {{tag.name}}{% endblock title %}
{% block page %}
<form method="post" id="tag-form">{% csrf_token %}
    {{ form.as_p }}
    <section class="form-button-section">
        <input class="form-button" type="submit" value="Save">
        <a class="link-button" href="{% url 'restaurant_tracker:tag_index' %}">Exit</a>
        {% comment %} <a href="{% url 'restaurant_tracker:tag_delete' tag.id %}"><i style="visibility:visible;" class="fas fa-trash-alt"></i></a> {% endcomment %}
    </section>
</form>
<form class="delete-form" method="post" action="{% url 'restaurant_tracker:tag_delete' tag.id %}">{% csrf_token %}
    <button class="image-button" type="submit"><i style="visibility:visible;" class="fas fa-trash-alt"></i></button>
</form>
{% endblock page %}

restaurant_tracker/templates/restaurant_tracker/tags.html
{% extends "restaurant_tracker/base_tag.html" %}
{% load static %}
{% block title %}Tag List{% endblock title %}
{% block page %}
<h1 class="inline-h1">Tags</h1>
{% comment %} <input type="text" id="search-bar" onkeyup="myFunction()" placeholder="Search tags..."> {% endcomment %}
{% if tag_list %}
    <table id="tag-table">
    <tr>
        <td colspan="1">
            <section>
                <a class="add-new" href="{% url 'restaurant_tracker:tag_create' %}">Add tag</a>
            </section>
        </td>
    </tr>
    {% for tag in tag_list %}
        <tr>
            <td id="name-column">
                <a href="{% url 'restaurant_tracker:tag_edit' tag.id %}">
                    {% include "restaurant_tracker/tag_display_snippet.html" with tag=tag%}
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p> No tags are available.</p>
{% endif %}
<div id="filter-sidebar">

</div>
{% comment %} <script>
    function myFunction() {
    // Declare variables
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("restaurantList");
    li = ul.getElementsByTagName('li');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
        } else {
        li[i].style.display = "none";
        }
    }
    }
</script> {% endcomment %}
{% endblock page %}